### ISSUE TITLE
C++ ".h" header files are always detected as C headers

### ISSUE THREAD

**Issue by aaronfranke** [Aaronepower/tokei#305] opened 2019-02-20 17:48 UTC
The current definition for C++ headers looks like this:

```
            "extensions":[
                "hh",
                "hpp",
                "hxx",
                "inl",
                "ipp"
]
```

However, this incorrectly identifies C++ header files as C, as seen with this front-end program:

![deepinscreenshot_select-area_20190216225726](https://user-images.githubusercontent.com/13710835/52905722-7f808100-323e-11e9-95cd-485879aabeb1.png)

What this is missing from the above definition is `.h`, which is commonly used for both C and C++. Detecting which is which may be a little bit tricky. I suggest inspecting the code of [GitHub Linguist](https://github.com/github/linguist) to see how it detects this (as it does so properly).

To test if it works or not, you can test on Godot. It should show up as about 94.4% C++ code.

**Comment by Aaronepower** [comment] 2019-02-21 09:17
@aaronfranke Thank you for your issue! This is at least some what of a duplicate of #67. So I'm going to close this issue in favour of that. I will say that these kinds of "mistakes" are quite intentional as I don't like the idea of language detection being something that is obfuscated or nondeterministic. 

However there is definitely more language detection methods on the table that are quite deterministic (like  modeline) that I do want to add to tokei, and for the rest of the cases I want to provide easy configuration so that you the user gets what they expect.

**Closed by Aaronepower** 2019-02-21 09:17 UTC
