### ISSUE TITLE
print vs println for different output formats

### ISSUE THREAD

**Issue by jtmelton** [Aaronepower/tokei#132] opened 2017-07-12 05:06 UTC
I'm trying to wrap this tool, and the tool is working fine for the default format, but not for the specified formats. I'm not a rust person, but my best guess is that it could be either the difference between print for specified formats (https://github.com/Aaronepower/tokei/blob/master/src/input.rs#L129) vs println for the default (https://github.com/Aaronepower/tokei/blob/master/src/main.rs#L165), or possibly that the IO buffer for stdout is not getting flushed properly. Does this sound right?

**Comment by Aaronepower** [comment] 2017-07-12 12:06
Hello, and thanks for your issue! Can I what specifically the problem is? Is there an error or is the output malformed in some way? Also the two links you provided are the same link. 😛

**Comment by jtmelton** [comment] 2017-07-12 17:09
@Aaronepower sorry for the bad links ... updated them in the original issue. As for what the problem is, I'm trying to wrap this tool (I happen to be using java for this), and consume the output to be fed into other tools. As such, I'd like to use json. The issue is that when I consume the output, it succeeds if I run 'tokei mydir/', but just blocks if I run 'tokei mydir/ --output json'. It seems that something isn't getting flushed or responding. It blocks on the Process#waitFor call.

**Comment by Aaronepower** [comment] 2017-07-16 03:16
@jtmelton Could you provide me with a MVE(Minimum Verifiable Example) of your Java code that I can run on my machine and test against?

**Comment by jtmelton** [comment] 2017-07-16 03:36
@Aaronepower sure ...

```
public static void main(String[] args) throws Exception {
    Runtime r = Runtime.getRuntime();
    Process p = r.exec("/path/to/tokei --output json /path/to/source");
    int exitCode = p.waitFor();
    System.err.println("exit code: " + exitCode);
}
```

**Comment by Aaronepower** [comment] 2017-07-16 15:27
@jtmelton Hmm I can run this just fine on my mac. What OS are you using and what version of tokei are you using?

**Comment by jtmelton** [comment] 2017-07-17 02:35
@Aaronepower Ubuntu 16.04 LTS and tokei v6.0.2

**Comment by Aaronepower** [comment] 2017-09-03 22:56
Closing as cannot replicate.

**Closed by Aaronepower** 2017-09-03 22:56 UTC
