### ISSUE TITLE
Option to override extensions?

### ISSUE THREAD

**Issue by kaushalmodi** [Aaronepower/tokei#116] opened 2017-04-13 14:08 UTC
Hello,

I am not a Rust programmer but I was following the `CONTRIBUTING/md` to add support for Verilog and SystemVerilog.

So I added these to the `languages.json` (in alphabetical order):

```json
        "SystemVerilog":{
            "base":"c",
            "extensions":[
                "sv",
                "svh"
            ]
        },
```

```json
        "Verilog":{
            "base":"c",
            "extensions":[
                "v",
                "vg"
            ]
        },
```

But then on building, I get:

```
   Compiling tokei v6.0.0 (file:///home/kmodi/downloads/git/tokei)
error[E0001]: unreachable pattern
   --> /home/kmodi/downloads/git/tokei/target/x86_64-unknown-linux-musl/release/build/tokei-cfa6d5ef49951a7c/out/language_type.rs:875:25
    |
875 |                         "v" |
    |                         ^^^ this is an unreachable pattern

error: aborting due to previous error

error: Could not compile `tokei`.
```

I believe it's because the `.v` extension is already taken by Coq:

```json
        "Coq":{
            "base":"func",
            "extensions":[
                "v"
            ]
        },
```

I have never coded in Coq.. So would there be a way to add a smarter detection of languages.. based on some language keywords may be? Or simply config options?

**Comment by kaushalmodi** [comment] 2017-04-13 14:13
Another such conflict with 

```json
        "ObjectiveC":{
            "name":"Objective C",
            "base":"c",
            "extensions":[
                "m"
            ]
        },
```

All my `.m` files are Matlab scripts.. makes more sense.. *m for Matlab* :)

**Comment by Aaronepower** [comment] 2017-04-13 14:44
Closing this a duplicate of #67

**Closed by Aaronepower** 2017-04-13 14:44 UTC
