### ISSUE TITLE
Number of files tallying doesn't work

### ISSUE THREAD

**Issue by petevine** [Aaronepower/tokei#44] opened 2016-06-06 22:25 UTC
It seems piping output around doesn't update the file total, plus, only the file types from the final command are being tallied.
 
````
~$  tokei usercorn-unstable/
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 Go                    149         9163         7886          298          979
 Makefile                1           26           18            0            8
 Markdown                3          254          254            0            0
 Python                  2          154          125            2           27
 YAML                    1           20           17            0            3
-------------------------------------------------------------------------------
 Total                 156         9617         8300          300         1017
-------------------------------------------------------------------------------


~$  tokei go/src/github.com/
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 BASH                    1            8            6            1            1
 C Header                6         3435         2939          400           96
 Go                    170        29590        25755         1492         2343
 Markdown               13         1090         1090            0            0
 Python                  2          130          101            9           20
 YAML                    6           69           65            0            4
-------------------------------------------------------------------------------
 Total                 198        34322        29956         1902         2464
-------------------------------------------------------------------------------

~$  tokei -o json go/src/github.com/ | tokei -i stdin usercorn-unstable/
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 Go                    149        38753        33641         1790         3322
 Makefile                1           26           18            0            8
 Markdown                3         1344         1344            0            0
 Python                  2          284          226           11           47
 YAML                    1           89           82            0            7
-------------------------------------------------------------------------------
 Total                 163        43939        38256         2202         3481
-------------------------------------------------------------------------------
````

**Comment by Aaronepower** [comment] 2016-06-07 00:40
Can you add and section the results of these two commands so I can see where the problem is 

# Multiple paths

```
$ tokei usercorn_stable/, go/src/github.com
```

# Output to file

```
$ tokei usercorn_stable/ -o json > stats.json

$ tokei go/src/github.com/ -i stats.json
```

**Comment by petevine** [comment] 2016-06-07 12:14
The first command works as expected:
````
~$  tokei usercorn-unstable/, go/src/github.com
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 BASH                    1            8            6            1            1
 C Header                6         3435         2939          400           96
 Go                    319        38753        33641         1790         3322
 Makefile                1           26           18            0            8
 Markdown               16         1344         1344            0            0
 Python                  4          284          226           11           47
 YAML                    7           89           82            0            7
-------------------------------------------------------------------------------
 Total                 354        43939        38256         2202         3481
-------------------------------------------------------------------------------
````

while dumping to file and reading from it:
````
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 BASH                    1            8            6            1            1
 C Header                6         3435         2939          400           96
 Go                    170        38753        33641         1790         3322
 Markdown               13         1344         1344            0            0
 Python                  2          284          226           11           47
 YAML                    6           89           82            0            7
-------------------------------------------------------------------------------
 Total                 199        43939        38256         2202         3481
-------------------------------------------------------------------------------
````

Attaching the the json files:

[json-files.zip](https://github.com/Aaronepower/tokei/files/302507/json-files.zip)

**Comment by petevine** [comment] 2016-06-07 12:16
Was the multiple paths syntax always there?

**Comment by Aaronepower** [comment] 2016-06-07 12:51
@petevine Yep, since before it was called tokei.

**Comment by petevine** [comment] 2016-06-07 12:54
Oops, thx!

**Comment by Aaronepower** [comment] 2016-06-07 13:10
@petevine What version of tokei is this? you can get that from.

```
$ tokei -V
```

**Comment by petevine** [comment] 2016-06-07 14:21
It's `2.1.1`.

**Comment by Aaronepower** [comment] 2016-06-11 12:45
Fixed by 3.0.0

**Closed by Aaronepower** 2016-06-11 12:45 UTC

**Comment by petevine** [comment] 2016-06-11 12:59
Indeed! Looking at the combined results of tokei + deps, I'd like to suggest a feature, inverting the `-e` flag, i.e. include just one or more language types.

That way the contents of `.cargo` or `go` directories could be filtered out easily.

Thx!

**Comment by Aaronepower** [comment] 2016-06-11 13:06
@petevine Isn't this already solved by using glob patterns?

**Comment by petevine** [comment] 2016-06-11 14:18
You mean the `-e` flag should contain an expression excluding everything but `.rs` files, for example? 

It would be faster and easier to choose a language directly, I think.

**Comment by Aaronepower** [comment] 2016-06-11 14:20
@petevine No I mean something like 

```
tokei **/*.rs
```

**Comment by petevine** [comment] 2016-06-11 14:23
Ah, ok - for a moment I thought it was doing language type detection, regardless of any extension. Thanks.
