### ISSUE TITLE
Panic when piping output to less and quitting before all output displayed on Windows

### ISSUE THREAD

**Issue by iliekturtles** [Aaronepower/tokei#68] opened 2016-09-21 13:53 UTC
See below for reproduction steps. Once the "Counting files..." portion finishes if you scroll down to view the first couple files and then quit the panic will be shown. I haven't been able to see if the same issue occurs on Linux yet.

Likely any `print!` and `println!` invocations should be changed to `write!` or `writeln!` so that the `Result` can be handled.

```
$ cargo install tokei
$ RUST_BACKTRACE=1 tokei . --files | less
thread 'main' panicked at 'failed printing to stdout: The pipe is being closed. (os error 232)', ../src/libstd\io\stdio.rs:617
thread '<unnamed>' panicked at 'failed printing to stdout: The pipe is being closed. (os error 232)', ../src/libstd\io\stdio.rs:617
stack backtrace:
   0:        0x13f4e00ec - <unknown>
   1:        0x13f4df6f9 - <unknown>
   2:        0x13f4cd05d - <unknown>
   3:        0x13f4e272b - <unknown>
   4:        0x13f4cdf5f - <unknown>
   5:        0x13f4d62e3 - <unknown>
   6:        0x13f2a22ad - <unknown>
   7:        0x13f4df0cc - <unknown>
   8:        0x13f4e27c1 - <unknown>
   9:        0x13f4dee04 - <unknown>
  10:        0x13f2cfdc9 - <unknown>
  11:        0x13f4ec1d8 - <unknown>
  12:         0x76d459bc - BaseThreadInitThunk
```

https://github.com/rust-lang/rust/blob/1.11.0/src/libstd/io/stdio.rs#L617

**Comment by Aaronepower** [comment] 2016-09-21 17:56
@iliekturtles What is your rustc version? `rustc -vV` and what are you running this through? MSYS or Cygwin?

**Comment by iliekturtles** [comment] 2016-09-21 18:04
Original report was using MSys (mintty distributed with git-for-window). I can also reproduce the same issue in the command prompt using more.com (see below).

```
$ rustc -vV
rustc 1.11.0 (9b21dcd6a 2016-08-15)
binary: rustc
commit-hash: 9b21dcd6a89f38e8ceccb2ede8c9027cb409f6e3
commit-date: 2016-08-15
host: x86_64-pc-windows-msvc
release: 1.11.0
```

```
>tokei . --files | C:\Windows\System32\more.com
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
thread 'main' panicked at 'thread 'failed printing to stdout: The pipe is being
closed. (os error 232)<unnamed>', ' panicked at '../src/libstd\io\stdio.rsfailed
 printing to stdout: The pipe is being closed. (os error 232):617',
../src/libstd\io\stdio.rsnote: Run with `RUST_BACKTRACE=1` for a backtrace.
:617
D:\Code\FST-support>
```

**Comment by Aaronepower** [comment] 2016-09-21 18:22
@iliekturtles Well I do think that tokei should panic if it can't lock the stdout. However I think the solution to the problem is to just lock stdout at the beginning and not let go till we're done.

**Comment by iliekturtles** [comment] 2016-09-22 02:05
Similar failure on Linux. I did a bit of digging and cargo/rustc mostly `try!(write!(...))` but I didn't determine how a broken pipe is considered a benign error.

```
$ RUST_BACKTRACE=1 tokei . --files | less
thread 'main' panicked at 'thread 'failed printing to stdout: Broken pipe (os error 32)<unnamed>', ' panicked at '../src/libstd/io/stdio.rsfailed printing to stdout: Broken pipe (os error 32):', 617../src/libstd/io/stdio.rs
:stack backtrace:
617
   1:     0x55e16611946f - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:     0x55e16611cceb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:     0x55e16611c96f - std::panicking::default_hook::heb8b6fd640571a4f
   4:     0x55e16610ec2e - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:     0x55e16611cf31 - std::panicking::begin_panic::h941ea76fc945d925
   6:     0x55e16610f6fa - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   7:     0x55e16611448b - std::io::stdio::_print::h91aef6f665f00d62
   8:     0x55e166040f23 - tokei::main::h22cd5cedabf244ab
   9:     0x55e16611c578 - std::panicking::try::call::hca715a47aa047c49
  10:     0x55e16612454b - __rust_try
  11:     0x55e1661244ee - __rust_maybe_catch_panic
  12:     0x55e16611c01e - std::rt::lang_start::h162055cb2e4b9fe7
  13:     0x7fb6c9de6730 - __libc_start_main
  14:     0x55e16603f1d8 - _start
  15:                0x0 - <unknown>
stack backtrace:
   1:     0x55e16611946f - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:     0x55e16611cceb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:     0x55e16611c96f - std::panicking::default_hook::heb8b6fd640571a4f
   4:     0x55e16610ec2e - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:     0x55e16611cf31 - std::panicking::begin_panic::h941ea76fc945d925
   6:     0x55e16610f6fa - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   7:     0x55e16611448b - std::io::stdio::_print::h91aef6f665f00d62
   8:     0x55e16604b148 - std::panicking::try::call::hf2b3bea75f57d4a1
   9:     0x55e16612454b - __rust_try
  10:     0x55e1661244ee - __rust_maybe_catch_panic
  11:     0x55e16604bba6 - _<F as alloc..boxed..FnBox<A>>::call_box::hf57e2e77a29f27f1
  12:     0x55e16611b514 - std::sys::thread::Thread::new::thread_start::hf2eed4b6f7149599
  13:     0x7fb6ca3a65c9 - start_thread
  14:     0x7fb6c9ec8eac - __clone
  15:                0x0 - <unknown>
```

**Comment by oif** [comment] 2016-12-04 03:09
Same on mac.

```
rustc 1.13.0 (2c6933acc 2016-11-07)
binary: rustc
commit-hash: 2c6933acc05c61e041be764cb1331f6281993f3f
commit-date: 2016-11-07
host: x86_64-apple-darwin
release: 1.13.0
```

```
NeoMacBook-Pro:~ neo$ RUST_BACKTRACE=1 tokei Development --output json
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(KeyMustBeAString, 0, 0)', ../src/libcore/result.rs:799
stack backtrace:
   1:        0x105efa0a8 - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:        0x105efd2ff - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:        0x105efc395 - std::panicking::default_hook::h0ac3811ec7cee78c
   4:        0x105efc9a6 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:        0x105efc844 - std::panicking::begin_panic::h6ed03353807cf54d
   6:        0x105efc762 - std::panicking::begin_panic_fmt::hc321cece241bb2f5
   7:        0x105efc6c7 - rust_begin_unwind
   8:        0x105f287b0 - core::panicking::panic_fmt::h27224b181f9f037f
   9:        0x105d71b1a - core::result::unwrap_failed::h9916702f61d59849
  10:        0x105da3f30 - tokei::main::h788afbac7a995aa4
  11:        0x105efd8ba - __rust_maybe_catch_panic
  12:        0x105efbed6 - std::rt::lang_start::h538f8960e7644c80
```

**Comment by Aaronepower** [comment] 2016-12-04 09:57
@oif Your issue is different serde is failing to convert to json. Can you file a seperate issue for that?

**Comment by oif** [comment] 2016-12-04 11:32
@Aaronepower Ok, done. And sorry about that.

**Comment by Aaronepower** [comment] 2017-01-02 23:01
I'm going to mark this as wontfix, as I don't know how to fix it, and can't replicate it.

**Closed by Aaronepower** 2017-01-02 23:01 UTC
Labels: bug, help wanted
